[package]
name = "native_app"
version = "0.1.0"
authors = ["Aaron R Miller <aaron.miller@waweb.io>"]

[dependencies.ffi]
package = "native_app_sys"
path = "../native_app_sys"

[lib]
crate_type = ["staticlib", "cdylib"]