[package]
name = "native_app"
version = "0.1.2"
authors = ["Aaron R Miller <aaron.miller@waweb.io>"]
license = "MIT"
keywords = ["android", "ndk", "camera"]
readme = "../README.md"

[dependencies]
jni = "0.5.2"

[lib]
crate_type = ["staticlib", "dylib"]
